# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='works',
            name='datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
