# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170615_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.User'),
        ),
    ]
