# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170615_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='content',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name=' 提交故障'),
        ),
    ]
